### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by sekimura** [sekimura/wipasswd#11]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/wipasswd
  Reason: image not found
Trace/BPT trap: 5

**Comment by Tatsh** [comment]
The binary should be updated but really why? Make a tag and add the binary to the release. ~~Maybe build with `-mmacosx-version-min=10.10`?~~

**Comment by sekimura** [comment]
Using travis or fastlane to do pipeline things would be better to build binary rather than using brew.
